### ISSUE TITLE
Incident Date in discover app will not allow selection of current date

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#204]

**Comment by alexmcode** [comment]
@smcgregor after looking at the code, the greyed out dates are meant to be max and min limits for date selection given by algolie for this specific fields - incident_date and published_date. Selecting dates above/below these barriers and sending the query to algolia will give an empty list of incident reports. So these barriers help the user not get lost in the range filter. Should we remove these limitations?

**Comment by alexmcode** [comment]
To make sure you had experience the same as what I'm explaining - this is it right?

![image](https://user-images.githubusercontent.com/7571224/127478808-2080abf9-e8fb-45fa-bdcf-d8052055f4ba.png)

The user can't select `29th to July` (today) even if it's the current date (because the maximum value of `incident_date` in all incident reports is `10th of July 2021`)

**Comment by smcgregor** [comment]
I don't think people should be able to select for older incidents than exist, but being able to select today for the date filter would clear up some confusion since this behavior is not expected. I am also OK with being able to select into the future since the URL could be shared and visited later.

**Comment by alexmcode** [comment]
Ok in this case I would say to limit only the min end and not the max also. So people can select into the future including current date where is the case

**Comment by smcgregor** [comment]
Sounds good.
