### ISSUE TITLE
Incident taxonomy (descriptions and/or tags)

### ISSUE THREAD

**Issue by yunque** [PartnershipOnAI/aiid#43]
**Background**
[Incident lists](https://incidentdatabase.ai/summaries/incidents) are currently enumerated but lack a short description that encompasses the nature of the incident, or a tagging system to describe key aspects of the incident.

**Proposal**
To include a short one-line description of each incident, and potentially also a tagging system. This could be built on a taxonomy of incidents describing key aspects, such as:
- stakeholders affected (e.g. children, workers, drivers)
- use case (e.g. facial recognition, justice, autonomous vehicles, industrial automation, finance, legal)
- technology (e.g. prediction, classification, automated decision, bots)
- severity (e.g. lethal, offensive)
- norms (e.g. racism, sexism)
- values (e.g. safety, privacy, discrimination, misinformation)
- location (e.g. US, China)

**Benefit**
A taxonomy would help different users, such as:
- Lawyers: tracking legal cases related to specific incidents, seeking related cases
- Educators: providing case studies for students
- Civil rights advocates: understanding AI harms in their domain of advocacy
- Database maintainers: validate reports more easily 
- Database contributors: submit metadata along with report submission
- Civil society: find relevant case studies more easily on the website's [incident list](https://incidentdatabase.ai/summaries/incidents)

**Requirements**
- develop the taxonomy
- add descriptions/tags to the incident list
- new fields in the database
- new fields in the submission form
- define taxonomy format (CSV or JSON, and corresponding field names)

**Comment by smcgregor** [comment]
Hi @yunque!

First off, this is a well thought out and excellent issue to kick things off taxonomy-wise. There are details on how this is built architecturally [in the paper](https://arxiv.org/abs/2011.08512) that will be helpful in the discussion. You have several taxonomies proposed in this incident, and each one needs to have its own definition and managing users and/or organizations. Do you have one specifically you would like to build out? I can light the path. :)

Regarding the description, I am considering associating each incident with its earliest known descriptive headline, but I am not eager to have the database as an "authoritative" entity issuing descriptions of incidents and thereby shaping how the incident is viewed. For example, impacted parties will seek more negative characterizations of intent while the organizations producing the intelligent system will lobby for more charitable characterizations. Another way to inject descriptions is to make it more of a wiki/community managed field, but we need to develop community norms and processes first. Let's concentrate on an initial taxonomy and come back to descriptions?

**Comment by yunque** [comment]
Hi @smcgregor!

Thanks for the link to the paper. Now I understand better the motivation for simply numbering the incidents (mirroring other incident databases such as CVE) and avoiding opinionated incident descriptions. I wonder if there is nevertheless some sort of "simplest" objective description that may avoid any particular perspective bias, but I agree, better begin with the taxonomies.

Would you consider that stakeholders, use cases, technhology, etc. each require their own taxonomy?

I've started looking for literature on taxonomy definition to see if there's any specific method for developing one. I'm starting with NTSB and CVE, following the work you reported in the paper. Do you already have some ideas on this that I can build on or is it pretty much greenfield?

**Comment by smcgregor** [comment]
Taxonomies for the AIID is like writing a taxonomy for life on earth, but there is a new speciation event every 10 minutes. To compensate we can work within namespaces that can be migrated to new versions in the face of definitional issues. Due to the architecture of the AIID, all taxonomies will be available to all applications and summaries that may want to consume them.

The steps for implementing a taxonomy are the following,

0. Fork this repository in the GitHub UI.
1. Create a feature branch for your taxonomy, `feature-MY-TAXONOMY-HERE`.
2. Create a folder for taxonomies in [this folder](https://github.com/PartnershipOnAI/aiid/tree/master/site/gatsby-site/content)
3. Add the taxonomies folder to the list [here](https://github.com/PartnershipOnAI/aiid/blob/master/site/gatsby-site/config.js#L51). This will add it to the navigation.
4. Create `1-TAXONOMYNAMEHERE.mdx` in the taxonomies folder. The taxonomy name will be its namespace.
5. Write documentation for the taxonomy in the `1-TAXONOMYNAMEHERE.mdx`. You can look at [an example mdx file](https://github.com/PartnershipOnAI/aiid/blob/master/site/gatsby-site/content/about_apps/1-discover.mdx) to see the formatting that can go in the file. It is a derivative of [markdown](https://en.wikipedia.org/wiki/Markdown#Example)

**What to put in the taxonomy doc?**

It depends! You should look at it from the perspective of what the doc needs to accomplish.

* What information would be required so that a person not involved in applying the taxonomy has the information needed to apply the taxonomy? This is closely related to the concept of qualitative coding, where the key attribute is inter-rater reliability-- a person applying the same code set should with some percentage of consistency (reliability) apply the same classifications.
* What information would be required so that a person consuming the taxonomy (e.g., writing a research paper derived from the classification population statistics) would correctly interpret the taxonomy?

Now you can open a merge request for discussion of the documentation. At the time we merge, I will add support for it into the backend.

Note: I recommend avoiding hierarchical taxonomies at the moment. There are plenty of useful flat taxonomies that should be applied first and they are much easier to manage.

**Comment by smcgregor** [comment]
Oh, and I believe you can likely do the docs part without needing to get the local dev environment setup. We have not tested it yet, but I believe pull requests will hook into the build system and generate a preview. You can be the first to try from a fork! Of course, if you do setup a dev environment feel free to ask questions and improve the startup docs. :)

**Comment by smcgregor** [comment]
@yunque this [PR](https://github.com/PartnershipOnAI/aiid/pull/166) has much of what you ask for. You can see it previewed [here](https://deploy-preview-166--aiid.netlify.app/research/4-taxonomies). Please comment here if you have any input. I am closing this issue in favor of #92 , but please reopen or comment here if you would like to continue the discussion.
