### ISSUE TITLE
Move parsing news endpoint to a Netlify function

### ISSUE THREAD

**Issue by cesarvarela** [PartnershipOnAI/aiid#467]
Considering that everything is already set up to use Netlify functions through Gatsby, the only thing left would be to find a library that extracts article data.

Something like https://github.com/ageitgey/node-unfluff.

This would fix the cold start problems of the current endpoint.

**Comment by smcgregor** [comment]
The Netlify functions often backend on AWS Lambda functions. I think the problem is that this endpoint is a docker container rather than using the standard Lambda environment. This may make the startup time much longer. I think this issue should be something about improving the parsing endpoint performance.

**Comment by smcgregor** [comment]
After talking, I am good with giving unfluff a try as either a netlify function or a new AWS function. I'll assign you on this one.
